version: "3"
services:
    app:
        build: .
        volumes:
            - .:/usr/src/barebones-blog
        ports:
            - "3000:3000"
        depends_on:
            - mongo
              # command: npm run devstart
    mongo:
        image: mongo
        ports:
            - "27017:27017"
